import 'dart:math';

import 'package:goal_setting/data_classes/vehicle.dart';

import '../global/api_caller.dart';
import '../global/global_settings.dart';

// Nissan - Car, Van
// BMW - Car, SUV
// Volkswagen - Car , SUV, EV
// Toyota - Car, EV, SUV
// Hyundai - Car, SUV
//
// Electric Vehicle
// SUV
// Van
// Car

import 'dart:convert';
import 'package:http/http.dart' as http;

 sendDataToBackend(List<Vehicle> dummyData) async {
  // Instantiate the API caller object
  ApiCaller apiCaller = ApiCaller(baseUrl: globalData.baseUrlRoute);

  // Iterate through DummyData and send each Vehicle object to the backend
  for (Vehicle vehicle in dummyData) {
    // Convert Vehicle object to JSON
    Map<String, dynamic> jsonBody = vehicle.toJson();

    // Call the API to send data to the backend
    final response = await apiCaller.callApi('save_vehicle', jsonBody);

    if (response != null && response['success'] == true) {
      // Data sent successfully
      print('Vehicle data sent successfully.');
    } else {
      // Failed to send data
      print('Failed to send vehicle data. Please try again.');
    }
  }
}




final List<Vehicle> DummyData = [
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Sunny',
      power: 100,
      numberOfPeople: 5,
      capacityForBags: 2,
      priceInDollars: 60.0,
      pricePerKilometer: 0.25,
      priceForDriverPerDay: 25.0,
      numberOfVehiclesAvailable: 5,
      description: 'The Nissan Sunny is a reliable and spacious sedan suitable for family outings and city commutes. With its fuel-efficient engine and comfortable interior, it provides a smooth driving experience for passengers.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Almera',
      power: 110,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 65.0,
      pricePerKilometer: 0.27,
      priceForDriverPerDay: 28.0,
      numberOfVehiclesAvailable: 3,
      description: 'The Nissan Almera is a versatile and stylish sedan designed for urban adventures and long drives. Its spacious cabin and advanced safety features make it an ideal choice for both solo travelers and families.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Micra',
      power: 90,
      numberOfPeople: 4,
      capacityForBags: 2,
      priceInDollars: 55.0,
      pricePerKilometer: 0.22,
      priceForDriverPerDay: 20.0,
      numberOfVehiclesAvailable: 4,
      description: 'The Nissan Micra is a compact and agile hatchback perfect for navigating crowded city streets with ease. Its fuel-efficient engine and nimble handling make it an excellent choice for urban commuters.',
      imageUrl: ''
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Elantra',
    power: 147,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 220.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Hyundai Elantra is a compact car that offers style, performance, and efficiency. With its spacious interior and advanced safety features, it\'s perfect for everyday commuting and weekend road trips.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Sonata',
    power: 191,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 240.0,
    pricePerKilometer: 0.85,
    priceForDriverPerDay: 110.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Hyundai Sonata is a midsize sedan that offers comfort, convenience, and performance. With its sleek design and advanced technology, it\'s perfect for both daily commuting and long-distance travel.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Accent',
    power: 120,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 190.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Hyundai Accent is a subcompact car that offers efficiency, reliability, and affordability. With its compact size and fuel-efficient engine, it\'s perfect for city driving and urban exploration.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Venue',
    power: 121,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 95.0,
    numberOfVehiclesAvailable: 9,
    description: 'The Hyundai Venue is a compact crossover that offers versatility, style, and performance. With its modern design and advanced technology, it\'s perfect for urban adventurers and weekend road trips.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Ioniq Hybrid',
    power: 139,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 230.0,
    pricePerKilometer: 0.85,
    priceForDriverPerDay: 105.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Hyundai Ioniq Hybrid is a fuel-efficient car that offers eco-friendly driving and advanced technology. With its hybrid powertrain and spacious interior, it\'s perfect for drivers who want to reduce their carbon footprint without sacrificing performance.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Kona',
    power: 147,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 240.0,
    pricePerKilometer: 0.9,
    priceForDriverPerDay: 110.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Hyundai Kona is a subcompact SUV that offers style, versatility, and performance. With its rugged design and advanced safety features, it\'s perfect for urban exploration and weekend adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Palisade',
    power: 291,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 300.0,
    pricePerKilometer: 0.95,
    priceForDriverPerDay: 120.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Hyundai Palisade is a full-size SUV that offers luxury, comfort, and performance. With its spacious interior and premium features, it\'s perfect for family road trips and weekend getaways.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Tucson',
    power: 187,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 250.0,
    pricePerKilometer: 0.9,
    priceForDriverPerDay: 115.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Hyundai Tucson is a compact SUV that offers comfort, performance, and versatility. With its spacious cabin and advanced technology, it\'s perfect for both daily commuting and weekend adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Santa Fe',
    power: 191,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 260.0,
    pricePerKilometer: 0.95,
    priceForDriverPerDay: 120.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Hyundai Santa Fe is a midsize SUV that offers comfort, performance, and versatility. With its spacious interior and advanced safety features, it\'s perfect for family road trips and outdoor adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'Car',
    model: 'Venue',
    power: 121,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 95.0,
    numberOfVehiclesAvailable: 9,
    description: 'The Hyundai Venue is a compact crossover that offers versatility, style, and performance. With its modern design and advanced technology, it\'s perfect for urban adventurers and weekend road trips.',
    imageUrl: '',
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Versa',
      power: 95,
      numberOfPeople: 5,
      capacityForBags: 2,
      priceInDollars: 58.0,
      pricePerKilometer: 0.24,
      priceForDriverPerDay: 22.0,
      numberOfVehiclesAvailable: 6,
      description: 'The Nissan Versa is a sleek and modern sedan offering exceptional fuel efficiency and ample cargo space. Whether you\'re running errands in the city or embarking on a road trip, the Versa delivers a comfortable and enjoyable ride.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Altima',
      power: 120,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 70.0,
      pricePerKilometer: 0.28,
      priceForDriverPerDay: 30.0,
      numberOfVehiclesAvailable: 7,
      description: 'The Nissan Altima combines performance, comfort, and style in one impressive package. With its powerful engine, spacious interior, and advanced technology features, the Altima is the perfect choice for discerning drivers seeking an elevated driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Sunny',
      power: 100,
      numberOfPeople: 5,
      capacityForBags: 2,
      priceInDollars: 60.0,
      pricePerKilometer: 0.25,
      priceForDriverPerDay: 25.0,
      numberOfVehiclesAvailable: 5,
      description: 'The Nissan Sunny is a reliable and spacious sedan suitable for family outings and city commutes. With its fuel-efficient engine and comfortable interior, it provides a smooth driving experience for passengers.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Almera',
      power: 110,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 65.0,
      pricePerKilometer: 0.27,
      priceForDriverPerDay: 28.0,
      numberOfVehiclesAvailable: 3,
      description: 'The Nissan Almera is a versatile and stylish sedan designed for urban adventures and long drives. Its spacious cabin and advanced safety features make it an ideal choice for both solo travelers and families.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Micra',
      power: 90,
      numberOfPeople: 4,
      capacityForBags: 2,
      priceInDollars: 55.0,
      pricePerKilometer: 0.22,
      priceForDriverPerDay: 20.0,
      numberOfVehiclesAvailable: 4,
      description: 'The Nissan Micra is a compact and agile hatchback perfect for navigating crowded city streets with ease. Its fuel-efficient engine and nimble handling make it an excellent choice for urban commuters.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Versa',
      power: 95,
      numberOfPeople: 5,
      capacityForBags: 2,
      priceInDollars: 58.0,
      pricePerKilometer: 0.24,
      priceForDriverPerDay: 22.0,
      numberOfVehiclesAvailable: 6,
      description: 'The Nissan Versa is a sleek and modern sedan offering exceptional fuel efficiency and ample cargo space. Whether you\'re running errands in the city or embarking on a road trip, the Versa delivers a comfortable and enjoyable ride.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Nissan',
      type: 'Car',
      model: 'Altima',
      power: 120,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 70.0,
      pricePerKilometer: 0.28,
      priceForDriverPerDay: 30.0,
      numberOfVehiclesAvailable: 7,
      description: 'The Nissan Altima combines performance, comfort, and style in one impressive package. With its powerful engine, spacious interior, and advanced technology features, the Altima is the perfect choice for discerning drivers seeking an elevated driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'Car',
      model: '3 Series',
      power: 255,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 120.0,
      pricePerKilometer: 0.5,
      priceForDriverPerDay: 60.0,
      numberOfVehiclesAvailable: 5,
      description: 'The BMW 3 Series combines luxury and performance in a compact and stylish package. With its powerful engine and responsive handling, it delivers an exhilarating driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'Car',
      model: '5 Series',
      power: 335,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 150.0,
      pricePerKilometer: 0.6,
      priceForDriverPerDay: 70.0,
      numberOfVehiclesAvailable: 3,
      description: 'The BMW 5 Series offers exceptional comfort, performance, and technology features. With its spacious interior and advanced driver assistance systems, it\'s the perfect choice for both business and leisure travel.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'Car',
      model: '7 Series',
      power: 456,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 200.0,
      pricePerKilometer: 0.7,
      priceForDriverPerDay: 80.0,
      numberOfVehiclesAvailable: 2,
      description: 'The BMW 7 Series sets the standard for luxury and performance in the full-size sedan segment. With its powerful engine and opulent interior, it offers a first-class driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'Car',
      model: 'X1',
      power: 228,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 130.0,
      pricePerKilometer: 0.55,
      priceForDriverPerDay: 65.0,
      numberOfVehiclesAvailable: 4,
      description: 'The BMW X1 is a versatile and sporty compact SUV that offers ample cargo space and responsive handling. With its upscale interior and advanced technology features, it\'s perfect for urban adventures or long road trips.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'Car',
      model: 'X3',
      power: 248,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 140.0,
      pricePerKilometer: 0.6,
      priceForDriverPerDay: 70.0,
      numberOfVehiclesAvailable: 3,
      description: 'The BMW X3 combines the versatility of an SUV with the luxury and performance of a BMW. With its spacious interior and robust engine options, it\'s the perfect vehicle for everyday use or weekend getaways.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Golf',
      power: 147,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 100.0,
      pricePerKilometer: 0.4,
      priceForDriverPerDay: 50.0,
      numberOfVehiclesAvailable: 7,
      description: 'The Volkswagen Golf is a versatile and reliable compact car known for its spacious interior and fuel-efficient engine.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Passat',
      power: 174,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 120.0,
      pricePerKilometer: 0.45,
      priceForDriverPerDay: 60.0,
      numberOfVehiclesAvailable: 6,
      description: 'The Volkswagen Passat offers a comfortable ride, ample cargo space, and advanced technology features for a premium driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Jetta',
      power: 147,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 110.0,
      pricePerKilometer: 0.42,
      priceForDriverPerDay: 55.0,
      numberOfVehiclesAvailable: 5,
      description: 'The Volkswagen Jetta is a stylish and fuel-efficient sedan that delivers a smooth and enjoyable driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Tiguan',
      power: 184,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 130.0,
      pricePerKilometer: 0.48,
      priceForDriverPerDay: 65.0,
      numberOfVehiclesAvailable: 7,
      description: 'The Volkswagen Tiguan is a versatile and spacious SUV with comfortable seating and advanced safety features.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Arteon',
      power: 268,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 150.0,
      pricePerKilometer: 0.55,
      priceForDriverPerDay: 70.0,
      numberOfVehiclesAvailable: 6,
      description: 'The Volkswagen Arteon is a premium sedan that combines elegant design with powerful performance and advanced technology.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Beetle',
      power: 174,
      numberOfPeople: 4,
      capacityForBags: 2,
      priceInDollars: 90.0,
      pricePerKilometer: 0.35,
      priceForDriverPerDay: 45.0,
      numberOfVehiclesAvailable: 5,
      description: 'The Volkswagen Beetle is an iconic compact car with retro styling and nimble handling.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'Volkswagen',
      type: 'Car',
      model: 'Atlas',
      power: 276,
      numberOfPeople: 7,
      capacityForBags: 5,
      priceInDollars: 160.0,
      pricePerKilometer: 0.6,
      priceForDriverPerDay: 75.0,
      numberOfVehiclesAvailable: 8,
      description: 'The Volkswagen Atlas is a spacious and family-friendly SUV with seating for up to seven passengers and ample cargo space.',
      imageUrl: ''
  ),

  Vehicle(
    brand: 'Toyota',
    type: 'Car',
    model: 'Camry',
    power: 203,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 160.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 75.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota Camry is a reliable and fuel-efficient sedan that offers spacious seating for up to five passengers and ample cargo space. With its smooth ride and advanced safety features, it\'s perfect for both daily commuting and long road trips.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'Car',
    model: 'Corolla',
    power: 139,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 140.0,
    pricePerKilometer: 0.55,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota Corolla is a compact and fuel-efficient sedan that offers comfortable seating for up to five passengers and a smooth ride. With its reliable engine and affordable price, it\'s perfect for budget-conscious drivers.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'Car',
    model: 'Prius',
    power: 121,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 150.0,
    pricePerKilometer: 0.6,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Toyota Prius is a popular hybrid car known for its exceptional fuel efficiency and eco-friendly design. With its spacious interior and advanced technology features, it\'s perfect for environmentally-conscious drivers who want to reduce their carbon footprint.',
    imageUrl: '',
  ),




  Vehicle(
    brand: 'Volkswagen',
    type: 'Van',
    model: 'Transporter',
    power: 148,
    numberOfPeople: 9,
    capacityForBags: 8,
    priceInDollars: 100.0,
    pricePerKilometer: 0.4,
    priceForDriverPerDay: 50.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Volkswagen Transporter is a versatile and reliable van that offers ample space and comfortable seating for up to 9 passengers. With its efficient engine and spacious cargo area, it\'s perfect for family trips or commercial use.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'Van',
    model: 'Crafter',
    power: 138,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 90.0,
    pricePerKilometer: 0.35,
    priceForDriverPerDay: 45.0,
    numberOfVehiclesAvailable: 4,
    description: 'The Volkswagen Crafter is a reliable and versatile van that offers spacious seating for up to 8 passengers. With its powerful engine and flexible cargo space, it\'s perfect for transporting passengers or goods.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'Van',
    model: 'Multivan',
    power: 201,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 110.0,
    pricePerKilometer: 0.45,
    priceForDriverPerDay: 55.0,
    numberOfVehiclesAvailable: 3,
    description: 'The Volkswagen Multivan is a premium passenger van that offers luxurious amenities and spacious seating for up to 7 passengers. With its powerful engine and upscale interior, it\'s perfect for family vacations or corporate travel.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'Van',
    model: 'California',
    power: 174,
    numberOfPeople: 4,
    capacityForBags: 4,
    priceInDollars: 120.0,
    pricePerKilometer: 0.5,
    priceForDriverPerDay: 60.0,
    numberOfVehiclesAvailable: 2,
    description: 'The Volkswagen California is an iconic camper van that offers freedom and adventure on the open road. With its versatile interior and comfortable sleeping accommodations for up to 4 people, it\'s the perfect vehicle for outdoor enthusiasts.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'Van',
    model: 'Caravelle',
    power: 148,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 100.0,
    pricePerKilometer: 0.4,
    priceForDriverPerDay: 50.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Volkswagen Caravelle is a versatile and spacious van that offers comfortable seating for up to 8 passengers. With its flexible seating arrangements and ample cargo space, it\'s perfect for family trips or transporting goods.',
    imageUrl: '',
  ),








  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Santa Fe',
    power: 191,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 210.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Hyundai Santa Fe is a versatile SUV that offers comfort, performance, and safety. With its spacious interior and advanced technology, it\'s perfect for family adventures and daily commutes.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Tucson',
    power: 187,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 200.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 9,
    description: 'The Hyundai Tucson is a compact SUV that offers style, performance, and versatility. With its modern design and advanced features, it\'s perfect for urban driving and outdoor adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Palisade',
    power: 291,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 260.0,
    pricePerKilometer: 0.85,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Hyundai Palisade is a full-size SUV that offers luxury, performance, and capability. With its spacious cabin and advanced technology, it\'s perfect for family road trips and daily commutes.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Kona',
    power: 147,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 190.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Hyundai Kona is a subcompact SUV that offers agility, efficiency, and style. With its bold design and advanced features, it\'s perfect for urban adventures and weekend getaways.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Venue',
    power: 121,
    numberOfPeople: 5,
    capacityForBags: 2,
    priceInDollars: 180.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 10,
    description: 'The Hyundai Venue is a compact SUV that offers versatility, efficiency, and value. With its compact size and modern features, it\'s perfect for city driving and weekend adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Nexo',
    power: 161,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 250.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Hyundai Nexo is a hydrogen fuel cell SUV that offers zero-emission driving and advanced technology. With its eco-friendly design and spacious cabin, it\'s perfect for drivers who want to reduce their carbon footprint.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'Ioniq 5',
    power: 225,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 230.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 85.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Hyundai Ioniq 5 is an all-electric SUV that offers style, performance, and sustainability. With its futuristic design and long-range capabilities, it\'s perfect for eco-conscious drivers who want to make a statement.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'IONIQ 6',
    power: 214,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 240.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 95.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Hyundai Ioniq 6 is an all-electric sedan that offers performance, style, and efficiency. With its sleek design and advanced technology, it\'s perfect for drivers who want to embrace the future of mobility.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'IONIQ 7',
    power: 300,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 270.0,
    pricePerKilometer: 0.9,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Hyundai Ioniq 7 is a large SUV that offers space, comfort, and performance. With its three-row seating and advanced features, it\'s perfect for family road trips and outdoor adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Hyundai',
    type: 'SUV',
    model: 'IONIQ 9',
    power: 350,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 300.0,
    pricePerKilometer: 1.0,
    priceForDriverPerDay: 120.0,
    numberOfVehiclesAvailable: 4,
    description: 'The Hyundai Ioniq 9 is a luxury SUV that offers space, comfort, and performance. With its premium design and advanced technology, it\'s perfect for drivers who demand the best.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'RAV4',
    power: 203,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 200.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota RAV4 is a compact SUV that offers a blend of versatility and reliability. With its spacious interior and advanced safety features, it\'s perfect for both city driving and outdoor adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Highlander',
    power: 295,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 250.0,
    pricePerKilometer: 0.85,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota Highlander is a midsize SUV that offers comfort, convenience, and performance. With its spacious cabin and versatile seating options, it\'s perfect for family road trips and everyday use.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Land Cruiser',
    power: 381,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 300.0,
    pricePerKilometer: 0.9,
    priceForDriverPerDay: 120.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Toyota Land Cruiser is a full-size SUV that offers legendary off-road capability and luxury features. With its powerful engine and rugged design, it\'s perfect for exploring the great outdoors in style and comfort.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Sequoia',
    power: 381,
    numberOfPeople: 8,
    capacityForBags: 6,
    priceInDollars: 280.0,
    pricePerKilometer: 0.85,
    priceForDriverPerDay: 110.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Toyota Sequoia is a full-size SUV that offers impressive power, capability, and comfort. With its spacious interior and rugged design, it\'s perfect for family adventures and hauling heavy loads.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: '4Runner',
    power: 270,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 220.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 9,
    description: 'The Toyota 4Runner is a rugged SUV that offers exceptional off-road capability and durability. With its versatile cargo space and advanced technology, it\'s perfect for outdoor enthusiasts and adventurous families.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'C-HR',
    power: 144,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 190.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota C-HR is a stylish and compact SUV that offers sporty performance and modern design. With its agile handling and advanced safety features, it\'s perfect for urban driving and weekend getaways.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Venza',
    power: 219,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 210.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Toyota Venza is a sleek and versatile SUV that offers hybrid efficiency and premium comfort. With its spacious cabin and refined styling, it\'s perfect for drivers who want to elevate their daily commute.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'FJ Cruiser',
    power: 260,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 230.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota FJ Cruiser is a rugged and capable SUV that offers off-road performance and adventure-ready features. With its iconic design and powerful engine, it\'s perfect for exploring the great outdoors with confidence.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Corolla Cross',
    power: 169,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 200.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota Corolla Cross is a compact SUV that offers versatility, efficiency, and comfort. With its modern design and advanced technology, it\'s perfect for urban adventures and weekend road trips.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'SUV',
    model: 'Rush',
    power: 102,
    numberOfPeople: 7,
    capacityForBags: 3,
    priceInDollars: 180.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 9,
    description: 'The Toyota Rush is a compact SUV that offers practicality, versatility, and style. With its spacious interior and efficient engine, it\'s perfect for families and adventurers who value comfort and convenience.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'Tiguan',
    power: 184,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 150.0,
    pricePerKilometer: 0.6,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Volkswagen Tiguan is a versatile and spacious SUV that offers comfortable seating for five passengers and ample cargo space. With its smooth ride and fuel-efficient engine, it\'s perfect for both city driving and long road trips.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'Atlas',
    power: 276,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 180.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Volkswagen Atlas is a spacious and family-friendly SUV that offers seating for up to seven passengers and plenty of cargo space. With its powerful engine and advanced safety features, it\'s perfect for family road trips and daily commutes.',
    imageUrl: '',
  ),

  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'Touareg',
    power: 286,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Volkswagen Touareg is a luxurious and powerful SUV that offers exceptional performance and comfort. With its spacious interior and advanced technology features, it\'s perfect for both daily driving and long-distance travel.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'ID.4',
    power: 201,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 170.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 75.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Volkswagen ID.4 is an all-electric SUV that offers zero-emission driving without sacrificing performance or comfort. With its spacious interior and cutting-edge features, it\'s perfect for environmentally-conscious drivers.',
    imageUrl: '',
  ),

  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'Teramont',
    power: 276,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 190.0,
    pricePerKilometer: 0.75,
    priceForDriverPerDay: 85.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Volkswagen Teramont is a spacious and versatile SUV that offers seating for up to seven passengers and plenty of cargo space. With its powerful engine and advanced safety features, it\'s perfect for family adventures and daily drives.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'ID. Buzz',
    power: 201,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 180.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Volkswagen ID. Buzz is a modern and stylish electric SUV that offers a blend of retro design and cutting-edge technology. With its spacious interior and eco-friendly powertrain, it\'s perfect for urban driving and weekend getaways.',
    imageUrl: '',
  ),

  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'T-Cross',
    power: 113,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 140.0,
    pricePerKilometer: 0.55,
    priceForDriverPerDay: 65.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Volkswagen T-Cross is a compact and practical SUV that offers agile handling and modern features. With its versatile interior and fuel-efficient engine, it\'s perfect for city driving and weekend adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Volkswagen',
    type: 'SUV',
    model: 'ID. Crozz',
    power: 302,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Volkswagen ID. Crozz is an all-electric SUV that offers impressive performance and versatility. With its spacious interior and advanced technology features, it\'s perfect for eco-conscious drivers who demand both style and substance.',
    imageUrl: '',
  ),

  Vehicle(
      brand: 'BMW',
      type: 'SUV',
      model: 'X5',
      power: 335,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 160.0,
      pricePerKilometer: 0.65,
      priceForDriverPerDay: 75.0,
      numberOfVehiclesAvailable: 4,
      description: 'The BMW X5 is a luxurious and versatile SUV that offers impressive performance and comfort. With its spacious cabin and advanced technology features, it\'s perfect for family road trips or daily commuting.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'SUV',
      model: 'X6',
      power: 456,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 180.0,
      pricePerKilometer: 0.7,
      priceForDriverPerDay: 80.0,
      numberOfVehiclesAvailable: 3,
      description: 'The BMW X6 is a sleek and powerful SUV that combines sporty styling with premium features. With its dynamic performance and luxurious interior, it offers an exhilarating driving experience.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'SUV',
      model: 'X7',
      power: 523,
      numberOfPeople: 7,
      capacityForBags: 5,
      priceInDollars: 220.0,
      pricePerKilometer: 0.75,
      priceForDriverPerDay: 90.0,
      numberOfVehiclesAvailable: 2,
      description: 'The BMW X7 is a flagship luxury SUV that offers unparalleled comfort, performance, and technology features. With its spacious seating and upscale amenities, it\'s the ultimate choice for discerning drivers.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'SUV',
      model: 'X2',
      power: 228,
      numberOfPeople: 5,
      capacityForBags: 3,
      priceInDollars: 140.0,
      pricePerKilometer: 0.6,
      priceForDriverPerDay: 70.0,
      numberOfVehiclesAvailable: 3,
      description: 'The BMW X2 is a stylish and agile SUV that delivers sporty performance and premium features. With its compact size and versatile design, it\'s perfect for urban driving and weekend adventures.',
      imageUrl: ''
  ),
  Vehicle(
      brand: 'BMW',
      type: 'SUV',
      model: 'X4',
      power: 248,
      numberOfPeople: 5,
      capacityForBags: 4,
      priceInDollars: 150.0,
      pricePerKilometer: 0.65,
      priceForDriverPerDay: 75.0,
      numberOfVehiclesAvailable: 4,
      description: 'The BMW X4 combines the versatility of an SUV with the dynamic performance of a sports car. With its sleek coupe-like design and powerful engine options, it\'s the perfect vehicle for drivers who demand both style and substance.',
      imageUrl: ''
  ),



  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Prius Prime',
    power: 121,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 160.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota Prius Prime is a plug-in hybrid electric vehicle (PHEV) that offers excellent fuel efficiency and a spacious interior. With its advanced technology and comfortable ride, it\'s perfect for eco-conscious drivers who want to reduce their carbon footprint.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Mirai',
    power: 182,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 180.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Toyota Mirai is a hydrogen fuel cell electric vehicle (FCEV) that offers zero-emission driving with a long range and quick refueling times. With its futuristic design and advanced features, it\'s perfect for drivers who want a clean and sustainable transportation option.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'C-HR EV',
    power: 120,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 150.0,
    pricePerKilometer: 0.6,
    priceForDriverPerDay: 75.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Toyota C-HR EV is a compact electric SUV that offers agile handling and impressive fuel efficiency. With its stylish design and spacious interior, it\'s perfect for urban driving and weekend adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'e-Palette',
    power: 150,
    numberOfPeople: 6,
    capacityForBags: 5,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota e-Palette is a futuristic electric vehicle designed for autonomous transportation and mobile services. With its modular interior and customizable features, it\'s perfect for businesses and organizations looking for innovative mobility solutions.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'RAV4 EV',
    power: 154,
    numberOfPeople: 5,
    capacityForBags: 4,
    priceInDollars: 170.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 80.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota RAV4 EV is an all-electric SUV that offers excellent performance and versatility. With its spacious interior and advanced safety features, it\'s perfect for both daily driving and outdoor adventures.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Corolla Cross EV',
    power: 120,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 160.0,
    pricePerKilometer: 0.7,
    priceForDriverPerDay: 75.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Toyota Corolla Cross EV is an electric crossover SUV that offers a blend of style, comfort, and efficiency. With its spacious interior and advanced technology features, it\'s perfect for urban commuters and small families.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Yaris EV',
    power: 120,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 150.0,
    pricePerKilometer: 0.6,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 7,
    description: 'The Toyota Yaris EV is an all-electric hatchback that offers agile handling and impressive fuel efficiency. With its compact size and nimble performance, it\'s perfect for city driving and daily commutes.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Sienna EV',
    power: 201,
    numberOfPeople: 7,
    capacityForBags: 5,
    priceInDollars: 200.0,
    pricePerKilometer: 0.8,
    priceForDriverPerDay: 90.0,
    numberOfVehiclesAvailable: 8,
    description: 'The Toyota Sienna EV is an all-electric minivan that offers spacious seating and versatile cargo options. With its advanced features and smooth ride, it\'s perfect for family road trips and daily errands.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Supra EV',
    power: 335,
    numberOfPeople: 2,
    capacityForBags: 2,
    priceInDollars: 250.0,
    pricePerKilometer: 0.9,
    priceForDriverPerDay: 100.0,
    numberOfVehiclesAvailable: 6,
    description: 'The Toyota Supra EV is an all-electric sports car that offers exhilarating performance and sleek styling. With its powerful engine and agile handling, it\'s perfect for drivers who crave excitement behind the wheel.',
    imageUrl: '',
  ),
  Vehicle(
    brand: 'Toyota',
    type: 'EV',
    model: 'Prius EV',
    power: 120,
    numberOfPeople: 5,
    capacityForBags: 3,
    priceInDollars: 160.0,
    pricePerKilometer: 0.65,
    priceForDriverPerDay: 70.0,
    numberOfVehiclesAvailable: 5,
    description: 'The Toyota Prius EV is an all-electric version of the iconic hybrid car that started the eco-revolution. With its efficient design and advanced technology, it\'s perfect for drivers who want to reduce their carbon footprint without sacrificing performance.',
    imageUrl: '',
  ),





  // Add more dummy data for other Nissan cars if needed
];
